allowBuilds:
  esbuild: true
  workerd: true
  sharp: true

minimumReleaseAgeExclude:
  - '@svmd/content@0.2.0'
  - '@svmd/core@0.2.0'
  - '@svmd/mdast-util-svelte@0.2.0'
  - '@svmd/micromark-extension-svelte@0.2.0'
  - '@svmd/micromark-factory-svelte-expression@0.2.0'
  - '@svmd/vite@0.2.0'
  - '@sveltejs/adapter-cloudflare@8.0.0'
  - '@sveltejs/kit@3.0.0'
