/** Generated by `vite-plugin-coral-demos.js`: every docs demo's source, already highlighted. */
declare module 'virtual:coral-demo-sources' {
	export const sources: Record<string, { html: string; text: string }>;
}
